"""electronic signatures & multi-signer signature requests

Revision ID: 9a3f7c2e5b10
Revises: e7c4b2a1d9f8
Create Date: 2026-09-08 09:00:00.000000+00:00

Adds, additively:
  * ctms_electronic_signature              (Task 4.1 — one completed Part 11
                                            signature row, signed by a user
                                            over a document)
  * ctms_signature_requests                (Task 5.3 — multi-signer request
  * ctms_signature_request_signers          header + per-signer status)

ctms_signature_requests / ctms_signature_request_signers mirror the
fully-normalized v2 tables already defined in the authoritative SQL package
(03_operations_governance.sql) — column-for-column, including the
UNIQUE(request_id, user_id) constraint. ctms_electronic_signature is the new
singular ledger table from apps/eisf/models.py.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a3f7c2e5b10"
down_revision: Union[str, Sequence[str], None] = "e7c4b2a1d9f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ctms_electronic_signature",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("document_code", sa.String(length=64), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column(
            "signer_user_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("signer_name", sa.String(length=255), nullable=False),
        sa.Column("signer_role", sa.String(length=50), nullable=False),
        sa.Column("meaning", sa.String(length=50), nullable=False),
        sa.Column("signature_stamp", sa.String(length=512), nullable=False),
        sa.Column("signed_at", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["signer_user_id"], ["accounts_user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ctms_electronic_signature_document_code"),
        "ctms_electronic_signature",
        ["document_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_electronic_signature_document_id"),
        "ctms_electronic_signature",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ctms_electronic_signature_signer_user_id"),
        "ctms_electronic_signature",
        ["signer_user_id"],
        unique=False,
    )

    # document_id / study_id are plain columns in the ORM (the SQL package's
    # authoritative copy declares the FKs to ctms_documents / ctms_studies,
    # which have no SQLAlchemy model yet).
    op.create_table(
        "ctms_signature_requests",
        sa.Column(
            "request_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "study_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "requested_by",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["requested_by"], ["accounts_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_table(
        "ctms_signature_request_signers",
        sa.Column(
            "signer_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "request_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("signer_role", sa.String(length=100), nullable=True),
        sa.Column("signer_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("meaning", sa.String(length=255), nullable=True),
        sa.Column("signed_at", sa.DateTime(), nullable=True),
        sa.Column("verification_status", sa.String(length=50), nullable=True),
        sa.Column("certificate", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"], ["ctms_signature_requests.request_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("signer_id"),
        sa.UniqueConstraint("request_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ctms_signature_request_signers")
    op.drop_table("ctms_signature_requests")
    op.drop_index(
        op.f("ix_ctms_electronic_signature_signer_user_id"),
        table_name="ctms_electronic_signature",
    )
    op.drop_index(
        op.f("ix_ctms_electronic_signature_document_id"),
        table_name="ctms_electronic_signature",
    )
    op.drop_index(
        op.f("ix_ctms_electronic_signature_document_code"),
        table_name="ctms_electronic_signature",
    )
    op.drop_table("ctms_electronic_signature")
    # ### end Alembic commands ###