"""eisf repository, subject status history & governance scaffolding

Revision ID: e7c4b2a1d9f8
Revises: 70f65d974cc7
Create Date: 2026-09-07 10:00:00.000000+00:00

Adds, additively:
  * eisf_document / eisf_documentversion       (Task 2 — eISF repository + Part 11 versions)
  * ctms_subject_status_history                (Task 3 — append-only subject timeline)
  * ctms_complianceconfig / ctms_deviation / ctms_capa / ctms_auditevent /
    ctms_riskrule / ctms_riskscore / ctms_riskevent   (Task 6 — governance scaffolding)

Every table mirrors its SQLAlchemy model exactly (see apps/eisf/models.py and
apps/ctms/models.py). JSON-mirror rows use the same BIGINT-with-SQLite-variant
primary key idiom as the initial baseline migration.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7c4b2a1d9f8"
down_revision: Union[str, Sequence[str], None] = "70f65d974cc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ctms_record_columns():
    """The shared _CtmsRecord column set (identical to every ctms_* table)."""
    return [
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column(
            "organization_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("study_id", sa.String(length=100), nullable=True),
        sa.Column("site_id", sa.String(length=100), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    ]


def _ctms_record_indexes(table_name: str) -> None:
    op.create_index(op.f(f"ix_{table_name}_code"), table_name, ["code"], unique=False)
    op.create_index(
        op.f(f"ix_{table_name}_organization_id"),
        table_name,
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f(f"ix_{table_name}_study_id"), table_name, ["study_id"], unique=False
    )
    op.create_index(
        op.f(f"ix_{table_name}_site_id"), table_name, ["site_id"], unique=False
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eisf_document",
        *_ctms_record_columns(),
        sa.PrimaryKeyConstraint("id"),
    )
    _ctms_record_indexes("eisf_document")

    op.create_table(
        "eisf_documentversion",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("signed_by", sa.String(length=255), nullable=False),
        sa.Column("signature_stamp", sa.String(length=512), nullable=False),
        sa.Column("signed_at", sa.DateTime(), nullable=True),
        sa.Column("uploaded_by", sa.String(length=255), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["eisf_document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eisf_documentversion_code"), "eisf_documentversion", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_eisf_documentversion_document_id"),
        "eisf_documentversion",
        ["document_id"],
        unique=False,
    )

    for table_name in (
        "ctms_subject_status_history",
        "ctms_complianceconfig",
        "ctms_deviation",
        "ctms_capa",
        "ctms_auditevent",
        "ctms_riskrule",
        "ctms_riskscore",
        "ctms_riskevent",
    ):
        op.create_table(table_name, *_ctms_record_columns(), sa.PrimaryKeyConstraint("id"))
        _ctms_record_indexes(table_name)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in (
        "ctms_riskevent",
        "ctms_riskscore",
        "ctms_riskrule",
        "ctms_auditevent",
        "ctms_capa",
        "ctms_deviation",
        "ctms_complianceconfig",
        "ctms_subject_status_history",
    ):
        _drop_ctms_record_indexes(table_name)
        op.drop_table(table_name)

    op.drop_index(op.f("ix_eisf_documentversion_document_id"), table_name="eisf_documentversion")
    op.drop_index(op.f("ix_eisf_documentversion_code"), table_name="eisf_documentversion")
    op.drop_table("eisf_documentversion")

    _drop_ctms_record_indexes("eisf_document")
    op.drop_table("eisf_document")
    # ### end Alembic commands ###


def _drop_ctms_record_indexes(table_name: str) -> None:
    op.drop_index(op.f(f"ix_{table_name}_site_id"), table_name=table_name)
    op.drop_index(op.f(f"ix_{table_name}_study_id"), table_name=table_name)
    op.drop_index(op.f(f"ix_{table_name}_organization_id"), table_name=table_name)
    op.drop_index(op.f(f"ix_{table_name}_code"), table_name=table_name)