-- Required for gen_random_bytes() used by CTMS token generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

BEGIN;
CREATE TABLE IF NOT EXISTS organizations_organization (
 id BIGSERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS organizations_role (
 id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL,
 organization_id BIGINT NOT NULL REFERENCES organizations_organization(id) ON DELETE CASCADE,
 UNIQUE(organization_id,name)
);
CREATE TABLE IF NOT EXISTS accounts_user (
 id BIGSERIAL PRIMARY KEY,
 password VARCHAR(128) NOT NULL DEFAULT '', last_login TIMESTAMP NULL,
 is_superuser BOOLEAN NOT NULL DEFAULT FALSE, username VARCHAR(150) NOT NULL UNIQUE,
 first_name VARCHAR(150) NOT NULL DEFAULT '', last_name VARCHAR(150) NOT NULL DEFAULT '',
 is_staff BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 date_joined TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 email VARCHAR(254) NOT NULL UNIQUE, profile_photo VARCHAR(100),
 must_change_password BOOLEAN NOT NULL DEFAULT FALSE, failed_login_attempts INTEGER NOT NULL DEFAULT 5,
 session_token VARCHAR(32) NOT NULL DEFAULT encode(gen_random_bytes(16),'hex'),
 last_activity TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 pincode VARCHAR(10) NOT NULL DEFAULT '',
 organization_id BIGINT REFERENCES organizations_organization(id) ON DELETE SET NULL,
 role_id BIGINT REFERENCES organizations_role(id) ON DELETE SET NULL,
 scope_data JSONB
);
CREATE TABLE IF NOT EXISTS accounts_uploadeddocument (
 id BIGSERIAL PRIMARY KEY, document_number INTEGER UNIQUE, file VARCHAR(100) NOT NULL,
 original_name VARCHAR(255) NOT NULL, content_type VARCHAR(255), file_size BIGINT NOT NULL DEFAULT 0,
 category VARCHAR(50) NOT NULL DEFAULT 'general', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 organization_id BIGINT REFERENCES organizations_organization(id) ON DELETE CASCADE,
 uploaded_by_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS accounts_passwordresettoken (
 id BIGSERIAL PRIMARY KEY, token VARCHAR(32) UNIQUE, otp_code VARCHAR(6), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 expires_at TIMESTAMP, is_used BOOLEAN NOT NULL DEFAULT FALSE,
 user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS accounts_loginotp (
 id BIGSERIAL PRIMARY KEY, otp_code VARCHAR(6) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 expires_at TIMESTAMP, is_used BOOLEAN NOT NULL DEFAULT FALSE,
 user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS accounts_auditlog (
 id BIGSERIAL PRIMARY KEY, action VARCHAR(100) NOT NULL, ip_address VARCHAR(39), description TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, signature_token VARCHAR(32) NOT NULL UNIQUE,
 signature_meaning VARCHAR(255) NOT NULL DEFAULT '', user_id BIGINT REFERENCES accounts_user(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS accounts_uploadform (
 id BIGSERIAL PRIMARY KEY, file_name VARCHAR(255), form_type VARCHAR(20) NOT NULL, file VARCHAR(100) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS accounts_uploadlog (
 id BIGSERIAL PRIMARY KEY, file_name VARCHAR(255), action VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS monitoring_monitoringaccessrequest (
 id BIGSERIAL PRIMARY KEY, requester_role_label VARCHAR(100) NOT NULL DEFAULT '', start_date DATE NOT NULL, end_date DATE NOT NULL,
 reason TEXT NOT NULL DEFAULT '', status VARCHAR(20) NOT NULL DEFAULT 'pending', decision_note VARCHAR(255) NOT NULL DEFAULT '',
 decided_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 requested_by_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE, approved_by_id BIGINT REFERENCES accounts_user(id) ON DELETE SET NULL,
 site_id BIGINT NOT NULL REFERENCES organizations_organization(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS django_session (
 session_key VARCHAR(40) PRIMARY KEY, session_data TEXT NOT NULL, expire_date TIMESTAMP NOT NULL
);
COMMIT;
