BEGIN;
CREATE INDEX IF NOT EXISTS idx_accounts_user_org ON accounts_user(organization_id);
CREATE INDEX IF NOT EXISTS idx_accounts_user_role ON accounts_user(role_id);
CREATE INDEX IF NOT EXISTS idx_studies_org ON ctms_studies(organization_id);
CREATE INDEX IF NOT EXISTS idx_studies_status ON ctms_studies(status);
CREATE INDEX IF NOT EXISTS idx_sites_study ON ctms_sites(study_id);
CREATE INDEX IF NOT EXISTS idx_sites_org ON ctms_sites(organization_id);
CREATE INDEX IF NOT EXISTS idx_subjects_study ON ctms_subjects(study_id);
CREATE INDEX IF NOT EXISTS idx_subjects_site ON ctms_subjects(site_id);
CREATE INDEX IF NOT EXISTS idx_subjects_status ON ctms_subjects(status);
CREATE INDEX IF NOT EXISTS idx_visits_study ON ctms_visits(study_id);
CREATE INDEX IF NOT EXISTS idx_visits_site ON ctms_visits(site_id);
CREATE INDEX IF NOT EXISTS idx_visits_subject ON ctms_visits(subject_id);
CREATE INDEX IF NOT EXISTS idx_visits_date ON ctms_visits(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_docs_study ON ctms_documents(study_id);
CREATE INDEX IF NOT EXISTS idx_docs_site ON ctms_documents(site_id);
CREATE INDEX IF NOT EXISTS idx_docs_subject ON ctms_documents(subject_id);
CREATE INDEX IF NOT EXISTS idx_docs_module_section ON ctms_documents(module_id,section_id);
CREATE INDEX IF NOT EXISTS idx_doc_versions_doc ON ctms_document_versions(document_id);
CREATE INDEX IF NOT EXISTS idx_extractions_json ON ctms_document_extractions USING GIN(structured_data);
CREATE INDEX IF NOT EXISTS idx_monitoring_site ON ctms_monitoring_visits(site_id);
CREATE INDEX IF NOT EXISTS idx_issues_study ON ctms_issues(study_id);
CREATE INDEX IF NOT EXISTS idx_issues_site ON ctms_issues(site_id);
CREATE INDEX IF NOT EXISTS idx_risk_study ON ctms_risk_events(study_id);
CREATE INDEX IF NOT EXISTS idx_risk_site ON ctms_risk_events(site_id);
CREATE INDEX IF NOT EXISTS idx_risk_status ON ctms_risk_events(status);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_user ON ctms_ai_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation ON ctms_ai_messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON ctms_audit_events(entity_type,entity_key);
CREATE INDEX IF NOT EXISTS idx_audit_time ON ctms_audit_events(event_timestamp);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON ctms_notifications(user_id,is_read);
CREATE INDEX IF NOT EXISTS idx_comments_entity ON ctms_comments(entity_type,entity_key);
CREATE INDEX IF NOT EXISTS idx_ip_lots_site ON ctms_ip_lots(site_id);
CREATE INDEX IF NOT EXISTS idx_ip_tx_lot ON ctms_ip_transactions(lot_id);
CREATE INDEX IF NOT EXISTS idx_feasibility_study ON ctms_feasibility_candidates(study_id);
CREATE INDEX IF NOT EXISTS idx_ae_study ON ctms_adverse_events(study_id);
CREATE INDEX IF NOT EXISTS idx_engine_json_org ON ctms_amendment(organization_id);
CREATE INDEX IF NOT EXISTS idx_engine_json_study ON ctms_amendment(study_id);
CREATE INDEX IF NOT EXISTS idx_engine_json_site ON ctms_amendment(site_id);
CREATE INDEX IF NOT EXISTS idx_engine_json_data ON ctms_amendment USING GIN(data);

CREATE INDEX IF NOT EXISTS idx_ctms_amendment_org ON ctms_amendment(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_amendment_study ON ctms_amendment(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_amendment_site ON ctms_amendment(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_amendment_data ON ctms_amendment USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_iplot_org ON ctms_iplot(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_iplot_study ON ctms_iplot(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_iplot_site ON ctms_iplot(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_iplot_data ON ctms_iplot USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_irbsubmission_org ON ctms_irbsubmission(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_irbsubmission_study ON ctms_irbsubmission(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_irbsubmission_site ON ctms_irbsubmission(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_irbsubmission_data ON ctms_irbsubmission USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_icfversion_org ON ctms_icfversion(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_icfversion_study ON ctms_icfversion(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_icfversion_site ON ctms_icfversion(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_icfversion_data ON ctms_icfversion USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_consentevent_org ON ctms_consentevent(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_consentevent_study ON ctms_consentevent(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_consentevent_site ON ctms_consentevent(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_consentevent_data ON ctms_consentevent USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_reconsentcampaign_org ON ctms_reconsentcampaign(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_reconsentcampaign_study ON ctms_reconsentcampaign(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_reconsentcampaign_site ON ctms_reconsentcampaign(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_reconsentcampaign_data ON ctms_reconsentcampaign USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_vendor_org ON ctms_vendor(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_vendor_study ON ctms_vendor(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_vendor_site ON ctms_vendor(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_vendor_data ON ctms_vendor USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_kit_org ON ctms_kit(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_kit_study ON ctms_kit(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_kit_site ON ctms_kit(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_kit_data ON ctms_kit USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_feasibilitycandidate_org ON ctms_feasibilitycandidate(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_feasibilitycandidate_study ON ctms_feasibilitycandidate(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_feasibilitycandidate_site ON ctms_feasibilitycandidate(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_feasibilitycandidate_data ON ctms_feasibilitycandidate USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_feasibilityscoring_org ON ctms_feasibilityscoring(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_feasibilityscoring_study ON ctms_feasibilityscoring(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_feasibilityscoring_site ON ctms_feasibilityscoring(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_feasibilityscoring_data ON ctms_feasibilityscoring USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_safetyaecase_org ON ctms_safetyaecase(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_safetyaecase_study ON ctms_safetyaecase(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_safetyaecase_site ON ctms_safetyaecase(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_safetyaecase_data ON ctms_safetyaecase USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_monitoringrequest_org ON ctms_monitoringrequest(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_monitoringrequest_study ON ctms_monitoringrequest(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_monitoringrequest_site ON ctms_monitoringrequest(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_monitoringrequest_data ON ctms_monitoringrequest USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_subject_org ON ctms_subject(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_subject_study ON ctms_subject(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_subject_site ON ctms_subject(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_subject_data ON ctms_subject USING GIN(data);
CREATE INDEX IF NOT EXISTS idx_ctms_visit_org ON ctms_visit(organization_id);
CREATE INDEX IF NOT EXISTS idx_ctms_visit_study ON ctms_visit(study_id);
CREATE INDEX IF NOT EXISTS idx_ctms_visit_site ON ctms_visit(site_id);
CREATE INDEX IF NOT EXISTS idx_ctms_visit_data ON ctms_visit USING GIN(data);
COMMIT;
